import { PuzzleDefinitionLoader } from "../../../types/puzzle/PuzzleDefinition";
import { NumberPTM } from "../../../types/puzzle/PuzzleTypeMap";
import { PuzzleImportOptions } from "../../../types/puzzle/PuzzleImportOptions";
import { DigitPuzzleTypeManager } from "../../../puzzleTypes/default/types/DigitPuzzleTypeManager";
import { CellColor } from "../../../types/puzzle/CellColor";
import { Constraint } from "../../../types/puzzle/Constraint";
import { Position } from "../../../types/layout/Position";
import { RegionConstraint } from "../../../components/puzzle/constraints/region/Region";
import { PuzzleImporter } from "../PuzzleImporter";
import { PzlJsonGridParser } from "./PzlJsonGridParser";
import { PzlGeneratedSudokuData } from "./PzlPuzzleTypes";

const cell = (top: number, left: number): Position => ({ top, left });

const getDiagonalConstraints = (size: number): Constraint<NumberPTM>[] => [
    RegionConstraint(
        Array.from({ length: size }, (_, i) => cell(i, i)),
        false,
        "main diagonal 1",
    ),
    RegionConstraint(
        Array.from({ length: size }, (_, i) => cell(i, size - 1 - i)),
        false,
        "main diagonal 2",
    ),
];

const getDiagonalColors = (size: number) => {
    const initialColors: Record<number, Record<number, CellColor[]>> = {};

    for (let r = 0; r < size; r++) {
        const row = initialColors[r] ?? {};

        row[r] = [CellColor.lightGrey];
        row[size - 1 - r] = [CellColor.lightGrey];

        initialColors[r] = row;
    }

    return initialColors;
};

const addDiagonalSupport = (
    puzzle: ReturnType<PuzzleImporter<NumberPTM>["finalize"]>,
    data: PzlGeneratedSudokuData,
) => {
    if (!data.diagonal) {
        return puzzle;
    }

    const size = data.size ?? 9;
    const diagonalConstraints = getDiagonalConstraints(size);
    const originalItems = puzzle.items;

    return {
        ...puzzle,

        // Keep all constraints generated by the importer and add the two
        // diagonal "different" regions on top of them. PuzzleTV allows items to
        // be either an array or a function, so both cases must be handled.
        items: typeof originalItems === "function"
            ? (context: any) => [
                ...originalItems(context),
                ...diagonalConstraints,
            ]
            : [
                ...(originalItems ?? []),
                ...diagonalConstraints,
            ],

        // The SudokuChain4 implementation used the same light-grey highlighting
        // for diagonal sudoku. Keep the same visual convention here.
        initialColors: {
            ...(puzzle.initialColors ?? {}),
            ...getDiagonalColors(size),
        } as any,
    };
};

export const createPzlPuzzleDefinition = (data: PzlGeneratedSudokuData) => {
    const parser = new PzlJsonGridParser(data);

    const importOptions = {
        title: data.title,
        author: data.author,
    } as PuzzleImportOptions;

    const importer = new PuzzleImporter<NumberPTM>(
        data.slug,
        importOptions,
        DigitPuzzleTypeManager(),
        parser.gridSize,
    );

    importer.addGrid(parser);
    const puzzle = addDiagonalSupport(importer.finalize(), data);
    importer.dispose();

    return {
        ...puzzle,
        noIndex: false,
        slug: data.slug,
        saveStateKey: data.slug,
        typeManager: DigitPuzzleTypeManager(),
    };
};

/**
 * Creates a PuzzleTV loader from a mechanically generated PZL data object.
 */
export const createPzlPuzzle = (
    data: PzlGeneratedSudokuData,
): PuzzleDefinitionLoader<NumberPTM> => ({
    noIndex: false,
    slug: data.slug,

    loadPuzzle: () => createPzlPuzzleDefinition(data),
});
