import { PuzzleDefinitionLoader } from "../../../types/puzzle/PuzzleDefinition";
import { NumberPTM } from "../../../types/puzzle/PuzzleTypeMap";
import { PuzzleImportOptions } from "../../../types/puzzle/PuzzleImportOptions";
import { DigitPuzzleTypeManager } from "../../../puzzleTypes/default/types/DigitPuzzleTypeManager";
import { CellColor } from "../../../types/puzzle/CellColor";
import { Constraint } from "../../../types/puzzle/Constraint";
import { Position } from "../../../types/layout/Position";
import { RegionConstraint } from "../../../components/puzzle/constraints/region/Region";
import { PuzzleImporter } from "../PuzzleImporter";
import { PzlJsonGridParser } from "./PzlJsonGridParser";
import { PzlGeneratedSudokuData } from "./PzlPuzzleTypes";

const cell = (top: number, left: number): Position => ({ top, left });

const getDiagonalConstraints = (size: number): Constraint<NumberPTM>[] => [
    RegionConstraint(
        Array.from({ length: size }, (_, i) => cell(i, i)),
        false,
        "main diagonal 1",
    ),
    RegionConstraint(
        Array.from({ length: size }, (_, i) => cell(i, size - 1 - i)),
        false,
        "main diagonal 2",
    ),
];

const getDiagonalColors = (size: number) => {
    const initialColors: Record<number, Record<number, CellColor[]>> = {};

    for (let r = 0; r < size; r++) {
        const row = initialColors[r] ?? {};

        row[r] = [CellColor.lightGrey];
        row[size - 1 - r] = [CellColor.lightGrey];

        initialColors[r] = row;
    }

    return initialColors;
};

const createPairConstraint = (
    name: string,
    cell1: Position,
    cell2: Position,
    isAllowedPair: (value: number, otherValue: number) => boolean,
): Constraint<NumberPTM> => ({
    name,
    cells: [cell1, cell2],
    props: undefined,
    isObvious: true,

    isValidCell(cell, digits, cells, context) {
        const [firstCell, secondCell] = cells;
        const otherCell = cell.top === firstCell.top && cell.left === firstCell.left ? secondCell : firstCell;

        const valueData = digits[cell.top]?.[cell.left];
        const otherValueData = digits[otherCell.top]?.[otherCell.left];

        if (valueData === undefined || otherValueData === undefined) {
            return true;
        }

        const {
            typeManager: { getDigitByCellData },
        } = context.puzzle;

        const value = getDigitByCellData(valueData, context, cell);
        const otherValue = getDigitByCellData(otherValueData, context, otherCell);

        if (value === undefined || otherValue === undefined) {
            return true;
        }

        return isAllowedPair(value, otherValue);
    },
});

const NonConsecutivePairConstraint = (
    cell1: Position,
    cell2: Position,
): Constraint<NumberPTM> =>
    createPairConstraint(
        "non-consecutive pair",
        cell1,
        cell2,
        (value, otherValue) => Math.abs(value - otherValue) !== 1,
    );

const NoXVPairConstraint = (
    cell1: Position,
    cell2: Position,
): Constraint<NumberPTM> =>
    createPairConstraint(
        "no XV pair",
        cell1,
        cell2,
        (value, otherValue) => value + otherValue !== 5 && value + otherValue !== 10,
    );

const getOrthogonalPairConstraints = (
    size: number,
    factory: (cell1: Position, cell2: Position) => Constraint<NumberPTM>,
) => {
    const result: Constraint<NumberPTM>[] = [];

    for (let top = 0; top < size; top++) {
        for (let left = 0; left < size; left++) {
            const current = cell(top, left);

            if (left < size - 1) {
                result.push(factory(current, cell(top, left + 1)));
            }

            if (top < size - 1) {
                result.push(factory(current, cell(top + 1, left)));
            }
        }
    }

    return result;
};

const getExtraConstraints = (data: PzlGeneratedSudokuData): Constraint<NumberPTM>[] => {
    const size = data.size ?? 9;
    const result: Constraint<NumberPTM>[] = [];

    if (data.diagonal) {
        result.push(...getDiagonalConstraints(size));
    }

    if (data.nonConsecutive) {
        result.push(...getOrthogonalPairConstraints(size, NonConsecutivePairConstraint));
    }

    if (data.noXV) {
        result.push(...getOrthogonalPairConstraints(size, NoXVPairConstraint));
    }

    return result;
};

const addExtraConstraintSupport = (
    puzzle: ReturnType<PuzzleImporter<NumberPTM>["finalize"]>,
    data: PzlGeneratedSudokuData,
) => {
    const extraConstraints = getExtraConstraints(data);

    if (!extraConstraints.length && !data.diagonal) {
        return puzzle;
    }

    const size = data.size ?? 9;
    const originalItems = puzzle.items;

    return {
        ...puzzle,

        // Keep all constraints generated by the importer and add the extra
        // constraints on top of them. PuzzleTV allows items to be either an
        // array or a function, so both cases must be handled.
        items: typeof originalItems === "function"
            ? (context: any) => [
                ...originalItems(context),
                ...extraConstraints,
            ]
            : [
                ...(originalItems ?? []),
                ...extraConstraints,
            ],

        // The SudokuChain4 implementation used the same light-grey highlighting
        // for diagonal sudoku. Keep the same visual convention here. Other
        // extra constraints do not change the visual appearance.
        initialColors: data.diagonal
            ? ({
                ...(puzzle.initialColors ?? {}),
                ...getDiagonalColors(size),
            } as any)
            : puzzle.initialColors,
    };
};

export const createPzlPuzzleDefinition = (data: PzlGeneratedSudokuData) => {
    const parser = new PzlJsonGridParser(data);

    const importOptions = {
        title: data.title,
        author: data.author,
    } as PuzzleImportOptions;

    const importer = new PuzzleImporter<NumberPTM>(
        data.slug,
        importOptions,
        DigitPuzzleTypeManager(),
        parser.gridSize,
    );

    importer.addGrid(parser);
    const puzzle = addExtraConstraintSupport(importer.finalize(), data);
    importer.dispose();

    return {
        ...puzzle,
        noIndex: false,
        slug: data.slug,
        saveStateKey: data.slug,
        typeManager: DigitPuzzleTypeManager(),
    };
};

/**
 * Creates a PuzzleTV loader from a mechanically generated PZL data object.
 */
export const createPzlPuzzle = (
    data: PzlGeneratedSudokuData,
): PuzzleDefinitionLoader<NumberPTM> => ({
    noIndex: false,
    slug: data.slug,

    loadPuzzle: () => createPzlPuzzleDefinition(data),
});
